### ISSUE TITLE
No Installation Candidate for Bionic

### ISSUE THREAD

**Issue by Ginja** [GoogleCloudPlatform/osconfig#133]
After the last source update our new Ubuntu bionic builds are failing to find an installation candidate for google-osconfig-agent.

```
# cat /etc/apt/sources.list.d/google-osconfig-agent.list
deb http://packages.cloud.google.com/apt google-osconfig-agent-stretch-stable main
```

```
# apt-get update
...
...
# apt-get install -y google-osconfig-agent
...
...
...
E: Package 'google-osconfig-agent' has no installation candidate
```

`apt-get update` is also returning the following errors on our existing Bionic nodes. Was this Origin value change intentional?

https://packages.cloud.google.com/apt/dists/google-osconfig-agent-stretch-stable/InRelease

```
E: Repository 'http://packages.cloud.google.com/apt google-osconfig-agent-stretch-stable InRelease' changed its 'Origin' value from 'google-osconfig-agent-stretch' to 'google-osconfig-agent'
E: Repository 'http://packages.cloud.google.com/apt google-osconfig-agent-stretch-stable InRelease' changed its 'Label' value from 'google-osconfig-agent-stretch' to 'google-osconfig-agent'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```

**Comment by adjackura** [comment]
This was caused by a reshuffle with our repos. The new instructions are to point at the bionic repo for compuet engine:
deb http://packages.cloud.google.com/apt google-compute-engine-bionic-stable main

I'll look into fixing the old repo so it no longer throws that error as well

**Comment by adjackura** [comment]
I reverted the repo change, but it will it would be best to move to the new repo. We will be updating docs soon.
