### ISSUE TITLE
OSConfig Agent "unexpected end of JSON input"

### ISSUE THREAD

**Issue by Mo-Hussain** [GoogleCloudPlatform/osconfig#154]
I have a VM instance running Debian GNU/Linux 9 (stretch), it has the OSConfig Agent installed and running.  I have encountered the following error several times. 

```
 {
  "insertId": "ezj5okfzvhagf",
  "jsonPayload": {
    "localTimestamp": "2020-03-03T18:37:28.4900Z",
    "message": "unexpected end of JSON input"
  },
  "resource": {
    "type": "gce_instance",
    "labels": {
      "instance_id": "<INSTANCE_ID>",
      "zone": "us-central1-a",
      "project_id": "<PROJECT_ID>"
    }
  },
  "timestamp": "2020-03-03T18:37:28.737755265Z",
  "severity": "ERROR",
  "logName": "projects/<PROJECT_ID>/logs/OSConfigAgent",
  "sourceLocation": {
    "file": "main.go",
    "line": "154",
    "function": "main.runLoop"
  },
  "receiveTimestamp": "2020-03-03T18:37:30.853440003Z"
}
```
I have installed nodejs 12.16.1.

**Comment by adjackura** [comment]
Thanks for the feedback, this error is a result of a bad metadata read, this is not a huge issue and in most cases the agent will simple used the cached data. I will work on adding retries where appropriate and perhaps logging at a lower log level or with a much clearer message.

**Comment by Mo-Hussain** [comment]
Hi Andrew,

I believe this issue correlated with my VM crashing, I had a node process managed by pm2 which found that the VM was offline. I had to stop and start the VM on one occasion also to log in to it.

Best,
Mohammed

**Comment by mdkarp** [comment]
I also had a Debian VM running a regular processed that crashed after presenting this same error, and could not SSH into it after that.

**Comment by adjackura** [comment]
This error would be a potential indication of an issue on the instance but would not be the root cause of an issue like the instance crashing or logons failing. The osconfig agent simply logs any issues during the routine process of grabbing instance attributes, this is a GET call to the local metadata server, a corrupted response body would cause this error.

**Comment by alxndrsn** [comment]
I get a similar error logged sometimes at line 177:
```
{
  ...
  jsonPayload: {
    ...
    message: "unexpected end of JSON input"   
  }
  ...
  severity: "ERROR"
  sourceLocation: {
    file: "main.go"   
    function: "main.runLoop.func1"   
    line: "177"   
  }
}
```
It also appears as a separate log entry: `OSConfigAgent Error main.go:177: unexpected end of JSON input`.

Presumably this is the same class of error.

**Comment by alxndrsn** [comment]
Thanks @adjackura!

**Comment by puppeteer701** [comment]
I am also experiencing this but on line 229.
```
$ sudo systemctl status google-osconfig-agent
google-osconfig-agent.service - Google OSConfig Agent
     Loaded: loaded (/lib/systemd/system/google-osconfig-agent.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-05-20 22:39:14 UTC; 3 weeks 6 days ago
   Main PID: 427 (google_osconfig)
      Tasks: 11 (limit: 4694)
     Memory: 19.8M
        CPU: 4min 49.063s
     CGroup: /system.slice/google-osconfig-agent.service
             └─427 /usr/bin/google_osconfig_agent

May 20 22:39:14 k3s-qa-master systemd[1]: Started Google OSConfig Agent.
May 20 22:39:15 k3s-qa-master OSConfigAgent[427]: 2022-05-20T22:39:15.3256Z OSConfigAgent Info: OSConfig Agent (version 20220215.00-g1) started.
Jun 03 11:09:14 k3s-qa-master OSConfigAgent[427]: 2022-06-03T11:09:14.5179Z OSConfigAgent Error main.go:229: unexpected end of JSON input
```

I am running a *debian-11-bullseye-v20220406*.
