### ISSUE TITLE
[Regression] Fails to build on both ppc64le and s390x

### ISSUE THREAD

**Issue by glaubitz** [GoogleCloudPlatform/osconfig#263]
I recently tried to update the ```osconfig``` package in SUSE Linux Enterprise Server 12 and 15 to their latest upstream versions.

Unfortunately, the package fails to build on both ppc64le and s390x. In both cases, the failure is the same:

```
[   64s] + go build '-ldflags=-s -w -X main.version=20201117.00-1.6.1' -mod=vendor -o google_osconfig_agent
[   74s] # cos.googlesource.com/cos/tools.git/src/pkg/cos
[   74s] vendor/cos.googlesource.com/cos/tools.git/src/pkg/cos/env_reader.go:65:82: cannot use c.uname.Release[:] (type []uint8) as type []int8 in argument to charsToString
[   74s] error: Bad exit status from /var/tmp/rpm-tmp.SZQQ4F (%build)
```

I have not bisected the issue yet but earlier versions were not affected, so it's a regression.

**Comment by glaubitz** [comment]
Hmm, I tried looking into this but debugging Go source code is rather hard due to the various dependencies that are downloaded and built in a convoluted manner.

If this was C/C++ code, I would be able to help.

**Comment by adjackura** [comment]
We don't currently support either of those architectures. This issue looks like it's coming from the cos package, what we could do is add build tags to not include that functionality on those architectures as cos only gets built for amd64 (we already do this with this package as it doesn't build for Windows).
