### ISSUE TITLE
Unsuccessful recipes classed as installed

### ISSUE THREAD

**Issue by leg100** [GoogleCloudPlatform/osconfig#290]
If a recipe has a step that runs a script, and that script returns a non-allowed exit code, then the recipe correctly is recorded as unsuccessful. However, on the next run, the unsuccessful result is ignored, and OSConfig says the recipe is currently installed.

**Comment by adjackura** [comment]
Unfortunately this is WAI. We specifically only ever try to install a software recipe once to avoid broken recipes that keep installing over and over again (potentially consuming lots of resources). We are aware of the limitations with software recipes and are currently working on a much more flexible and powerful system.

**Comment by leg100** [comment]
I suspected as much. It is indeed unfortunate, if only because it's awfully confusing. But thank you for coming back to me so promptly. I look forward to the more powerful system!
