### ISSUE TITLE
Fails to build in Ubuntu

### ISSUE THREAD

**Issue by utkarsh2102** [GoogleCloudPlatform/osconfig#449]
Hello,

I am trying to update this package for Ubuntu archive and we have a build failure there. Here are the logs:
```
dpkg-buildpackage
-----------------

Command: dpkg-buildpackage -us -uc -sa -rfakeroot
dpkg-buildpackage: info: source package google-osconfig-agent
dpkg-buildpackage: info: source version 20220824.00-0ubuntu1
dpkg-buildpackage: info: source distribution lunar
dpkg-buildpackage: info: source changed by Utkarsh Gupta <utkarsh@debian.org>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
 debian/rules clean
dh clean --builddirectory=_build --buildsystem=golang --with=golang
   dh_auto_clean -O--builddirectory=_build -O--buildsystem=golang
dh_auto_clean: warning: LTO opimize is enable in buildflags. But cgo doesn't support it. LTO flags will be stripped in cgo.
   dh_autoreconf_clean -O--builddirectory=_build -O--buildsystem=golang
   debian/rules override_dh_clean
make[1]: Entering directory '/<<PKGBUILDDIR>>'
dh_clean vendor/
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
 dpkg-source -b .
dpkg-source: warning: Version number suggests Ubuntu changes, but there is no XSBC-Original-Maintainer field
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building google-osconfig-agent using existing ./google-osconfig-agent_20220824.00.orig.tar.gz
dpkg-source: info: building google-osconfig-agent in google-osconfig-agent_20220824.00-0ubuntu1.debian.tar.xz
dpkg-source: info: building google-osconfig-agent in google-osconfig-agent_20220824.00-0ubuntu1.dsc
 debian/rules binary
dh binary --builddirectory=_build --buildsystem=golang --with=golang
   dh_update_autotools_config -O--builddirectory=_build -O--buildsystem=golang
   dh_autoreconf -O--builddirectory=_build -O--buildsystem=golang
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/<<PKGBUILDDIR>>'
cp -r debian/extra/vendor ./
dh_auto_configure
dh_auto_configure: warning: LTO opimize is enable in buildflags. But cgo doesn't support it. LTO flags will be stripped in cgo.
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
   debian/rules override_dh_auto_build
make[1]: Entering directory '/<<PKGBUILDDIR>>'
dh_auto_build -O--buildsystem=golang -- -ldflags="-s -w -X main.version=20220824.00-0ubuntu1"
dh_auto_build: warning: LTO opimize is enable in buildflags. But cgo doesn't support it. LTO flags will be stripped in cgo.
_build/src/github.com/GoogleCloudPlatform/osconfig/e2e_tests/gcp_clients/gcp_clients.go:24:2: code in directory /<<PKGBUILDDIR>>/_build/src/github.com/GoogleCloudPlatform/osconfig/e2e_tests/internal/cloud.google.com/go/osconfig/apiv1 expects import "cloud.google.com/go/osconfig/apiv1"
	cd _build && go install -trimpath -v -p 8 "-ldflags=-s -w -X main.version=20220824.00-0ubuntu1"
package .: no Go files in /<<PKGBUILDDIR>>/_build
dh_auto_build: error: cd _build && go install -trimpath -v -p 8 "-ldflags=-s -w -X main.version=20220824.00-0ubuntu1" returned exit code 1
make[1]: *** [debian/rules:13: override_dh_auto_build] Error 25
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:6: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
--------------------------------------------------------------------------------
Build finished at 2022-11-10T11:46:32Z

Finished
--------
```

And it's not certain what's going wrong. Could you perhaps take a look and let us know if you have a clue or two? Thank you very much!

**Comment by utkarsh2102** [comment]
Just to be explicit about it, we're building this with `dh-golang` v1.59 and `golang` v1.19.2. I am not sure if that's resulting in this but we aren't really able to pin-point the exact reason. So stating this here as well.

**Comment by hopkiw** [comment]
Hi @utkarsh2102 

What has changed from the time when build was working to now? These build configs are owned by you, and we haven't done anything to the code that should cause this. Are other golang packages you maintain configured in the same way? Are they giving you this error?

**Comment by utkarsh2102** [comment]
Hi @hopkiw,

> What has changed from the time when build was working to now? These build configs are owned by you, and we haven't done anything to the code that should cause this. Are other golang packages you maintain configured in the same way? Are they giving you this error?

Nothing really changed. The `debian/` directory is as-is since the last version (20210608.1). I just unpacked the new upstream version (20220824.00) over it and have been seeing these weird failures. Only the version of dh-golang and golang itself changed. They're the newest. But nothing apart from that really changed.

There are other similar packages I maintain - google-guest-agent, oslogin, et al. I don't see any problems in their build. So this is specific to osconfig only. :/

**Comment by utkarsh2102** [comment]
> Only the version of dh-golang and golang itself changed. They're the newest. But nothing apart from that really changed.

Interesting discovery, meanwhile, heh..

So if I build this in 20.04 (Focal) which has older golang and dh-golang, I still get:
```
can't load package: _build/src/github.com/GoogleCloudPlatform/osconfig/e2e_tests/gcp_clients/gcp_clients.go:24:2: code in directory /<<PKGBUILDDIR>>/_build/src/github.com/GoogleCloudPlatform/osconfig/e2e_tests/internal/cloud.google.com/go/osconfig/apiv1 expects import "cloud.google.com/go/osconfig/apiv1"
```

but that's not deemed as a failure and the build proceeds, the tests run, they pass, and the build is successful. So something changed in newer Golang perhaps that considers the above error as fatal?

But irrespective of that, I think this should be fixed somehow - I am still not sure why is it looking for that. Any idea?

**Comment by utkarsh2102** [comment]
I think I understand some bits and pieces now. Super interesting (for me!). 

Upon bisecting the commits, I see that we have - https://github.com/GoogleCloudPlatform/osconfig/pull/432. This changes a few things. I still don't understand how or why but this definitely gets rid of the error now. Strange. Let me dig deeper.

**Comment by utkarsh2102** [comment]
Aaaaaah, of course. The failure was [...]osconfig/e2e_tests/internal/cloud.google.com/go/osconfig/apiv1 but we've stopped building that. Sweet. I think I can proceed with the builds. Need to update the vendored stuff, however.. :)

**Comment by hopkiw** [comment]
Thanks for keeping this issue up to date. Please continue to engage here if you need any help. It sounds like the issue was not related to our code, but to the build rules maintained by you, but let me know if I've misunderstood.
